name: example
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Junji Takakura <email@example.com>

environment:
  sdk: '>=2.0.0-dev.51.0 <2.0.0'

dependencies:
  spine_core: ^0.1.0
  spine_web:
    path: ../
  tuple: ^1.0.1

dev_dependencies:
  build_runner: ^0.8.7
  build_web_compilers: ^0.3.7
  test: ^0.12.30
